/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "secondary": "#aa3000",
        "secondary-bright": "#ff4d00",
        "on-secondary": "#ffffff",
        "secondary-container": "#d43f00",
        "on-secondary-container": "#fffbff",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "on-tertiary-container": "#848484",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#ffb59e",
        "on-secondary-fixed": "#3a0b00",
        "on-secondary-fixed-variant": "#852400",
        "tertiary-fixed": "#e4e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      maxWidth: {
        '1600': '1600px',
        'section': '1600px',
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4rem",
        "space-4xl": "6rem",
        "space-5xl": "8rem",
        "gutter-desktop": "2rem",
        "gutter-tablet": "1.5rem",
        "gutter-mobile": "1rem",
        "margin-desktop": "3.5rem",
        "margin-tablet": "2rem",
        "margin-mobile": "1.25rem"
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-xl-mobile": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-xl": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "body-xl": ["Manrope", "sans-serif"],
        "display-hero-mobile": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-index": ["Manrope", "sans-serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "display-hero": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-xl-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "68px", letterSpacing: "-0.035em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-xl": ["20px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "display-hero-mobile": ["56px", { lineHeight: "54px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-index": ["13px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "700" }],
        "display-hero": ["112px", { lineHeight: "96px", letterSpacing: "-0.05em", fontWeight: "800" }],
        "headline-lg": ["40px", { lineHeight: "46px", letterSpacing: "-0.025em", fontWeight: "700" }]
      },
      animation: {
        marquee: 'marquee 28s linear infinite',
        'marquee-reverse': 'marquee-reverse 28s linear infinite',
        'marquee-slow': 'marquee 40s linear infinite',
        'marquee-reverse-slow': 'marquee-reverse 45s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'marquee-reverse': {
          '0%': { transform: 'translateX(-50%)' },
          '100%': { transform: 'translateX(0%)' },
        }
      }
    },
  },
  plugins: [],
}
